name: Deploy wllama to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build root wllama package
        run: npm ci && npm run build

      - name: Install example deps
        run: npm ci
        working-directory: examples/main

      - name: Build example app
        run: npm run build
        working-directory: examples/main

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a
        with:
          branch: gh-pages
          folder: examples/main/dist
          clean: true
